
import type { NavItem } from "@/lib/types";
import {
    Building2,
    MessageCircle,
    Users,
    Banknote,
    User,
    UserCog,
    Shield,
    BookOpen,
    CalendarCheck,
    GraduationCap,
    Bus,
    Settings,
    NotebookText,
    ClipboardCheck,
    TrendingDown,
    BarChart2,
    BookUp,
    Map,
    MapPin,
    Wallet,
    FileBarChart,
  } from "lucide-react";

export const navItems: NavItem[] = [
    { title: "Admin", href: "/dashboard/admin", icon: Shield },
    { title: "Teacher", href: "/dashboard/teacher", icon: UserCog },
    { title: "Parent", href: "/dashboard/parent", icon: User },
    { title: "Student", href: "/dashboard/student", icon: User },
    { title: "Academics", href: "/dashboard/admin/academics", icon: GraduationCap },
    { title: "School Setup", href: "/dashboard/admin/setup", icon: Building2 },
    { title: "Student Management", href: "/dashboard/admin/student-management", icon: Users },
    { title: "Teacher Management", href: "/dashboard/admin/teacher-management", icon: UserCog },
    { title: "Fees Management", href: "/dashboard/admin/fees", icon: Banknote },
    { title: "Communication", href: "/dashboard/admin/communication", icon: MessageCircle },
    { title: "Library", href: "/dashboard/admin/library", icon: BookOpen },
    { title: "Transport", href: "/dashboard/admin/transport", icon: Bus },
    { title: "Routes & Stops", href: "/dashboard/admin/transport/routes", icon: Map },
    { title: "Vehicle Management", href: "/dashboard/admin/transport/vehicles", icon: Bus },
    { title: "Student Assignment", href: "/dashboard/admin/transport/student-assignment", icon: UserCog },
    { title: "Live Tracking", href: "/dashboard/admin/transport/live-tracking", icon: MapPin },
    { title: "Transport Fees", href: "/dashboard/admin/transport/fees", icon: Wallet },
    { title: "Reports", href: "/dashboard/admin/transport/reports", icon: FileBarChart },
    { title: "Attendance", href: "/dashboard/teacher/attendance", icon: CalendarCheck },
];
